# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2
jobs:
#   build:
#     docker:
#       - image: circleci/python
#         auth:
#           username: $username
#           password: $password
#         environment:
#           FLASK_CONFIG: testing
#     steps:
#       - run:
#           name: Setup VirtualEnv
#           command: |
#             echo 'export TAG=0.1.${CIRCLE_BUILD_NUM}' >> $BASH_ENV
#             echo 'export IMAGE_NAME=python-circleci-docker' >> $BASH_ENV 
#             virtualenv helloworld
#             . helloworld/bin/activate
#             pip install --no-cache-dir -r requirements.txt
#       - run:
#           name: Run Tests
#           command: |
#             . helloworld/bin/activate
#             python test_hello_world.py
#       - setup_remote_docker:
#           docker_layer_caching: true
#       - run:
#           name: Build and push Docker image
#           command: |
#             . helloworld/bin/activate
#             pyinstaller -F hello_world.py
#             docker build -t nanditatankha/docker .
#             echo $password | docker login --username $username --password-stdin
#             docker push nanditatankha/docker
  build:
    machine:
      enabled: true
      image: "ubuntu-1604:201903-01"
    steps:
      - run:
          name: Installing minikube
          command: |
            curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
            sudo install minikube-linux-amd64 /usr/local/bin/minikube
      - run:
          name: setting up minikube
          command: minikube start
      - run:
          name: deploy
          command:
            minikube kubectl -- get pods -- namespace kube-system

      # - run:
      #     name: deployment check for all the resources
      #     command: |
            


      